# 04_forbidden_edges_synthetic.py
# ============================================================
# Step 4 - Literature-reviewed causal constraints for synthetic data.
# Defines forbidden and required edges from human-approved
# RAG/literature claims after dataset-specific variable filtering.
#
# This file is generated by 11_finalize_constraints.py.
#
# Usage (standalone check):
#   python 04_forbidden_edges_synthetic.py
# ============================================================

from __future__ import annotations


# Each tuple: (source, target) means "forbid a causal arrow
# FROM source TO target".
FORBIDDEN_EDGES: list[tuple[str, str]] = [
    ("scope_2_emissions_tco2e", "total_energy_consumption"),  # tier=2; papers=[735c8d3e-d9bf-46cc-9420-0cc62447afb7, cd2205e2-02b5-49b1-a547-3e9f6f80295a]
    ("asset_growth_pct", "overall_esg_score"),  # tier=2; papers=[document_id:46fbff7b-0fac-479f-bb25-f855dff01f47]
    ("pe_ratio", "overall_esg_score"),  # tier=2; papers=[document_id:46fbff7b-0fac-479f-bb25-f855dff01f47]
    ("tobins_q", "overall_esg_score"),  # tier=2; papers=[document_id:46fbff7b-0fac-479f-bb25-f855dff01f47]
    ("scope_1_emissions_tco2e", "total_energy_consumption"),  # tier=2; papers=[8a9fdba1-8fb1-449e-bda2-5ebadebc602b]
    ("customer_satisfaction_score", "turnover_rate"),  # tier=2; papers=[turnover_performance_meta_analysis_hancock_2013]
    ("tobins_q", "scope_1_emissions_tco2e"),  # tier=3; papers=[0bc1c1a7-ff3b-43a1-b2cb-397cfc89a5c6, 2a14b689-090f-4c53-b3c4-bcd14ac3a69c, 87f984ed-e870-4647-b36a-b2f29b545528, b52a324f-b7a8-4def-8442-c6462110aa2a, bd8d8af6-2859-4844-a069-31a9f366e947, c12b4f71-c4b5-4b44-97e1-5acd47cb02bc, d9752059-5c45-4ca9-abb0-d9e936d03764, dca770f9-629a-4907-b840-4c7b0b96e8a3, dd25884f-4b9a-4e42-a5c8-f91f4506383f, e99e253d-f12d-41e7-975f-0ccb70bee838, eab148fd-5838-4671-9ab9-57c750281408, f76e31f2-f81b-479a-83d9-f765804ed9eb]
    ("roa_eat", "board_diversity"),  # tier=3; papers=[GOV-001, GOV-004, GOV-023]
    ("roa_eat", "emission_reduction_policy_score"),  # tier=3; papers=[28376774-e7fb-4268-8dcb-ed9642900c5d, 30ecac5c-0973-42d2-88f4-e01c7a81c9d9, 9f0ca1d1-4064-4da8-b485-45172efcdb01, b52a324f-b7a8-4def-8442-c6462110aa2a]
    ("roe_eat", "emission_reduction_policy_score"),  # tier=3; papers=[28376774-e7fb-4268-8dcb-ed9642900c5d, 30ecac5c-0973-42d2-88f4-e01c7a81c9d9, 9f0ca1d1-4064-4da8-b485-45172efcdb01, b52a324f-b7a8-4def-8442-c6462110aa2a]
    ("debt_to_equity_ratio", "scope_1_emissions_tco2e"),  # tier=3; papers=[5c2870ce-db2c-4a6a-96cb-9f238e8480df, 5c8e4da4-c087-4fef-bd83-c5177c3755c9, f3cceb1c-6c79-4e64-a7b5-5bf3296bd4a7]
    ("tobins_q", "board_diversity"),  # tier=3; papers=[GOV-002, GOV-008]
    ("roa_eat", "customer_satisfaction_score"),  # tier=3; papers=[customer_satisfaction_meta_analysis, customer_satisfaction_profitability_panel_data]
    ("debt_to_equity_ratio", "environmental_fines"),  # tier=3; papers=[3b163073-0466-4bc9-8d00-f02b5979bbfb, 48246c98-e8b6-4644-89bc-dc574bdeecf9]
    ("roa_eat", "iso_14001_exists"),  # tier=3; papers=[2bebb257-ed40-4aec-8f3f-8b15a0929d92, e8aeaba4-4b7d-4fca-93c6-96ef58b7062d]
    ("tobins_q", "iso_14001_exists"),  # tier=3; papers=[051316e6-fe7a-4bf4-a30b-d58d729d6d15, 2bebb257-ed40-4aec-8f3f-8b15a0929d92, 4703b56f-ee3b-4b2d-93fd-7c6cbf048ec8, e8aeaba4-4b7d-4fca-93c6-96ef58b7062d]
    ("tobins_q", "scope_2_emissions_tco2e"),  # tier=3; papers=[0bc1c1a7-ff3b-43a1-b2cb-397cfc89a5c6, 87f984ed-e870-4647-b36a-b2f29b545528, c12b4f71-c4b5-4b44-97e1-5acd47cb02bc, f7e75bfc-4d20-4a18-9d08-d6118ebc2d98]
    ("roa_eat", "turnover_rate"),  # tier=3; papers=[turnover_firm_performance_li_lourie_nekrasov_shevlin, turnover_performance_meta_analysis_hancock_2013]
    ("roe_eat", "auditor_independence_score"),  # tier=3; papers=[GOV-010]
    ("emission_reduction_policy_score", "board_diversity"),  # tier=3; papers=[GOV-007]
    ("overall_esg_score", "board_diversity"),  # tier=3; papers=[GOV-006]
    ("roe_eat", "board_diversity"),  # tier=3; papers=[GOV-003]
    ("emission_reduction_policy_score", "board_strategy_esg_oversight_score"),  # tier=3; papers=[GOV-020]
    ("roa_eat", "ceo_chair_split"),  # tier=3; papers=[GOV-012]
    ("overall_esg_score", "corruption_cases"),  # tier=3; papers=[GOV-016]
    ("roa_eat", "diversity_representation"),  # tier=3; papers=[gender_diversity_firm_performance_legitimacy]
    ("tobins_q", "diversity_representation"),  # tier=3; papers=[workforce_diversity_rd_innovation_firm_value]
    ("total_revenue_eur", "diversity_representation"),  # tier=3; papers=[gender_diversity_firm_performance_legitimacy]
    ("scope_1_emissions_tco2e", "roa_eat"),  # tier=3; papers=[36c08073-8f0e-405a-89b7-1df36c24f412]
    ("roa_eat", "scope_1_emissions_tco2e"),  # tier=3; papers=[b52a324f-b7a8-4def-8442-c6462110aa2a, d9752059-5c45-4ca9-abb0-d9e936d03764]
    ("roe_eat", "scope_1_emissions_tco2e"),  # tier=3; papers=[b52a324f-b7a8-4def-8442-c6462110aa2a, d9752059-5c45-4ca9-abb0-d9e936d03764]
    ("turnover_rate", "training_hours"),  # tier=3; papers=[training_productivity_wages_belgium]
]


# Each tuple: (source, target) means "require a causal arrow
# FROM source TO target".
REQUIRED_EDGES: list[tuple[str, str]] = [
    ("total_energy_consumption", "scope_2_emissions_tco2e"),  # tier=2; papers=[735c8d3e-d9bf-46cc-9420-0cc62447afb7, cd2205e2-02b5-49b1-a547-3e9f6f80295a]
    ("board_diversity", "roa_eat"),  # tier=3; papers=[GOV-001, GOV-004, GOV-023]
    ("emission_reduction_policy_score", "roa_eat"),  # tier=3; papers=[28376774-e7fb-4268-8dcb-ed9642900c5d, 30ecac5c-0973-42d2-88f4-e01c7a81c9d9, 9f0ca1d1-4064-4da8-b485-45172efcdb01, b52a324f-b7a8-4def-8442-c6462110aa2a]
    ("emission_reduction_policy_score", "roe_eat"),  # tier=3; papers=[28376774-e7fb-4268-8dcb-ed9642900c5d, 30ecac5c-0973-42d2-88f4-e01c7a81c9d9, 9f0ca1d1-4064-4da8-b485-45172efcdb01, b52a324f-b7a8-4def-8442-c6462110aa2a]
    ("scope_1_emissions_tco2e", "debt_to_equity_ratio"),  # tier=3; papers=[5c2870ce-db2c-4a6a-96cb-9f238e8480df, 5c8e4da4-c087-4fef-bd83-c5177c3755c9, f3cceb1c-6c79-4e64-a7b5-5bf3296bd4a7]
    ("board_diversity", "tobins_q"),  # tier=3; papers=[GOV-002, GOV-008]
    ("customer_satisfaction_score", "roa_eat"),  # tier=3; papers=[customer_satisfaction_meta_analysis, customer_satisfaction_profitability_panel_data]
    ("environmental_fines", "debt_to_equity_ratio"),  # tier=3; papers=[3b163073-0466-4bc9-8d00-f02b5979bbfb, 48246c98-e8b6-4644-89bc-dc574bdeecf9]
    ("iso_14001_exists", "roa_eat"),  # tier=3; papers=[2bebb257-ed40-4aec-8f3f-8b15a0929d92, e8aeaba4-4b7d-4fca-93c6-96ef58b7062d]
    ("iso_14001_exists", "tobins_q"),  # tier=3; papers=[051316e6-fe7a-4bf4-a30b-d58d729d6d15, 2bebb257-ed40-4aec-8f3f-8b15a0929d92, 4703b56f-ee3b-4b2d-93fd-7c6cbf048ec8, e8aeaba4-4b7d-4fca-93c6-96ef58b7062d]
    ("scope_2_emissions_tco2e", "tobins_q"),  # tier=3; papers=[0bc1c1a7-ff3b-43a1-b2cb-397cfc89a5c6, 87f984ed-e870-4647-b36a-b2f29b545528, c12b4f71-c4b5-4b44-97e1-5acd47cb02bc, f7e75bfc-4d20-4a18-9d08-d6118ebc2d98]
]


def build_background_knowledge(available_columns: list[str]):
    """
    Returns a causal-learn BackgroundKnowledge object with all
    forbidden and required edges that apply to the given columns.

    Parameters
    ----------
    available_columns : list of str
        Column names in the dataset.

    Returns
    -------
    bk : BackgroundKnowledge
    applied_forbidden : int
    applied_required : int
    """
    from causallearn.utils.PCUtils.BackgroundKnowledge import BackgroundKnowledge
    from causallearn.graph.GraphNode import GraphNode

    col_set = set(available_columns)
    node_map = {col: GraphNode(col) for col in available_columns}
    bk = BackgroundKnowledge()
    applied_forbidden = 0
    applied_required = 0
    skipped = []

    for src, tgt in FORBIDDEN_EDGES:
        if src in col_set and tgt in col_set:
            bk.add_forbidden_by_node(node_map[src], node_map[tgt])
            applied_forbidden += 1
        else:
            skipped.append(("forbidden", src, tgt))

    for src, tgt in REQUIRED_EDGES:
        if src in col_set and tgt in col_set:
            bk.add_required_by_node(node_map[src], node_map[tgt])
            applied_required += 1
        else:
            skipped.append(("required", src, tgt))

    print(f"[constraints] Forbidden edges applied : {applied_forbidden}")
    print(f"[constraints] Required edges applied  : {applied_required}")
    if skipped:
        print(f"[constraints] Skipped (cols not in data): {len(skipped)}")
        for kind, source, target in skipped:
            print(f"[constraints] {kind}: {source} -> {target}")

    return bk, applied_forbidden, applied_required


if __name__ == "__main__":
    print(f"[constraints] Forbidden edges defined : {len(FORBIDDEN_EDGES)}")
    print(f"[constraints] Required edges defined  : {len(REQUIRED_EDGES)}")
